1014TaoTao/fastapi_vue3_admin

frontend/src/components/TopCrumb/index.vue, frontend/src/components/TopTags/index.vue, frontend/src/layouts/basicLayout.vue, frontend/src/views/common/docs/index.vue, frontend/src/views/common/redoc/index.vue, frontend/src/views/dashboard/analysis.vue, frontend/src/views/dashboard/workplace.vue, frontend/src/views/monitor/cache/index.vue, frontend/src/views/monitor/online/index.vue, frontend/src/views/system/config/index.vue, frontend/src/views/system/dept/index.vue, frontend/src/views/system/dict/data.vue, frontend/src/views/system/dict/index.vue, frontend/src/views/system/job/index.vue, frontend/src/views/system/log/index.vue, frontend/src/views/system/menu/index.vue, frontend/src/views/system/notice/index.vue, frontend/src/views/system/position/index.vue, frontend/src/views/system/role/index.vue, frontend/src/views/system/user/index.vue
【功能优化】修改面包屑组件至顶部，统一面包屑组件至layout，增加tags页签简单功能
=> 【功能优化】修改面包屑组件至顶部，统一面包屑组件至layout，增加tags页签简单功能

backend/app/api/v1/services/system/auth_service.py, backend/app/core/router_class.py, backend/app/utils/ip_local_util.py, start.sh
- 在 LoginService 和 OperationLogRoute 中，将 request.client.host 转换为字符串后再传递给 IpLocalUtil.get_ip_location
- 在 IpLocalUtil 类中添加日志记录 IP 归属地获取过程
=> fix(ip): 修复登录时获取 IP 归属地的问题

backend/app/core/router_class.py
将OperationLogRoute类中的print语句替换为logger.info和logger.error，以提高日志记录的可维护性和可读性
=> refactor(router_class): 将print语句替换为logger记录

backend/app/core/router_class.py
将日志信息中的字符串拼接改为 f-string 格式，以提高代码可读性和性能。
=> style(router_class): 使用 f-string 优化日志信息格式

backend/app/utils/ip_local_util.py, backend/requirements.txt
为了提高IP归属地查询的性能和响应速度，将requests替换为httpx，并引入异步HTTP请求。同时，添加了备用API的注释以供未来使用。
=> feat(ip_local_util): 使用httpx替换requests以支持异步HTTP请求

start.sh
在部署脚本中引入全局变量，增加前端构建的检查逻辑，避免不必要的重新构建。同时优化了错误处理流程，提升脚本的健壮性和可维护性。
=> refactor: 优化部署脚本，增加前端构建检查

frontend/package-lock.json, frontend/package.json, frontend/src/router/index.js, frontend/vite.config.js
移除 `json-viewer-js` 和 `vuex` 等未使用的依赖，减少项目体积。优化 `vite.config.js` 中的打包配置，增加手动分包功能以提升构建性能。同时，将登录页面的组件改为动态导入，减少初始加载时间。
=> chore: 移除未使用的依赖并优化打包配置

backend/app/api/v1/controllers/system/config_controller.py, backend/app/api/v1/services/system/config_service.py
修复reids缓存配置过期导致接口无法正常获取系统配置问题
如果缓存过期则从数据库重新加载
=> fix: 修复reids缓存配置过期导致接口无法正常获取系统配置问题

.gitignore, frontend/.gitignore, frontend/package-lock.json, frontend/package.json
移除backend/app/config下的.env.dev和.env.dev1文件，并添加frontend/.gitignore中的package-lock.json。同时更新frontend/package.json中的vite版本至^5.4.19
=> chore: 更新.gitignore和package.json文件

frontend/.env.production
=> chore: 更新生产环境API基础地址

.gitignore, backend/env/.env.prod, docker-compose.yaml, frontend/.env.production
- 将敏感信息替换为生产环境实际配置
- 更新docker-compose中的数据库和redis配置
- 添加prod目录到.gitignore
- 统一前后端生产环境变量命名
=> chore: 更新生产环境配置和docker-compose设置

backend/app/utils/ip_local_util.py
之前切换到了ip-api.com API，现在恢复使用百度API，因为其返回的数据更详细且包含运营商信息
=> fix(ip_local_util): 恢复使用百度API获取IP归属地信息

frontend/src/layouts/basicLayout.vue, frontend/src/style.css
移除未使用的CSS变量--layout-main-height，并直接在logo-container中计算高度
=> fix(layout): 移除未使用的CSS变量并修复高度计算

frontend/package.json, frontend/vite.config.js
增加 Node.js 内存限制以避免构建时内存溢出
调整分包策略并添加文件命名规则以优化缓存
启用代码压缩并移除 console 和 debugger 语句
=> perf(frontend): 优化构建配置以提高性能和减小包体积

frontend/package.json, frontend/vite.config.js
- 移除package.json中build命令的NODE_OPTIONS参数
- 简化vite配置中的rollupOptions，保留手动分包功能但移除不必要的输出配置
- 移除生产环境下的console和debugger清除配置
=> refactor(frontend): 优化构建配置并移除冗余选项

start.sh
移除对docker-compose.yaml文件的前置检查，简化前端构建的条件判断
直接退出而非尝试添加执行权限当脚本无执行权限时
=> refactor(start.sh): 简化脚本逻辑并移除冗余检查

start.sh
- 重构项目路径和全局变量配置
- 改进权限检查和错误处理逻辑
- 增加项目首次克隆检测和前端变更检测
- 统一日志格式和步骤标识
- 优化容器管理和镜像清理流程
=> refactor(start.sh): 优化部署脚本结构和功能

frontend/src/views/current/configinfo.vue, frontend/src/views/current/profile.vue, frontend/src/views/system/auth/login.vue, frontend/src/views/system/config/index.vue, frontend/src/views/system/dept/index.vue, frontend/src/views/system/dict/data.vue, frontend/src/views/system/dict/index.vue, frontend/src/views/system/job/index.vue, frontend/src/views/system/log/index.vue, frontend/src/views/system/menu/index.vue, frontend/src/views/system/notice/index.vue, frontend/src/views/system/position/index.vue, frontend/src/views/system/role/PermissionDrawer.vue, frontend/src/views/system/role/index.vue, frontend/src/views/system/user/index.vue
统一移除各模块中API调用后的成功消息提示，简化代码结构
保留错误处理逻辑，仅通过控制台输出错误信息
=> refactor: 移除冗余的成功消息提示代码

frontend/package-lock.json, frontend/package.json, frontend/src/App.vue, frontend/src/main.js
=> feat: 添加页面加载进度条NProgress

frontend/src/layouts/components/Settings/index.vue, frontend/src/store/modules/user.store.ts, frontend/src/views/monitor/online/index.vue, frontend/src/views/monitor/server/index.vue, frontend/src/views/system/config/components/ConfigInfoDrawer.vue, frontend/src/views/system/config/index.vue, frontend/src/views/system/dict/components/DataDrawer.vue, frontend/src/views/system/dict/index.vue, frontend/src/views/system/log/index.vue, frontend/src/views/system/notice/index.vue, frontend/src/views/system/role/components/PermissonDrawer.vue, frontend/src/views/system/user/index.vue
- 为表格添加空数据提示组件
- 根据设备类型动态调整抽屉组件大小
- 优化表格列宽和显示效果
- 调整描述组件的列数布局
- 在重置用户状态时清除用户信息
=> feat: 优化前端界面布局和响应式设计

README.en.md, README.md, frontend/src/components/TableSelect/index.vue, frontend/src/layouts/components/NavBar/components/NavbarActions.vue, frontend/src/views/current/profile.vue, frontend/src/views/monitor/cache/index.vue, frontend/src/views/monitor/job/index.vue, frontend/src/views/monitor/online/index.vue, frontend/src/views/system/auth/components/Register.vue, frontend/src/views/system/auth/components/ResetPwd.vue, frontend/src/views/system/config/components/ConfigInfoDrawer.vue, frontend/src/views/system/config/index.vue, frontend/src/views/system/dept/index.vue, frontend/src/views/system/dict/components/DataDrawer.vue, frontend/src/views/system/dict/index.vue, frontend/src/views/system/log/index.vue, frontend/src/views/system/menu/index.vue, frontend/src/views/system/notice/index.vue, frontend/src/views/system/position/index.vue, frontend/src/views/system/role/index.vue, frontend/src/views/system/user/components/DeptTree.vue, frontend/src/views/system/user/index.vue, start.sh
refactor: 统一表单组件标签样式为冒号后缀
style: 调整按钮颜色和表单布局
fix(frontend): 添加取消强退的提示信息
chore: 调整部署脚本步骤顺序
=> fix: 修复表单标签样式和部署脚本顺序问题

frontend/package.json, frontend/src/layouts/components/NavBar/components/NavbarActions.vue, frontend/src/plugins/index.ts, frontend/src/views/monitor/job/index.vue, frontend/src/views/monitor/online/index.vue, frontend/src/views/system/config/components/ConfigInfoDrawer.vue, frontend/src/views/system/config/index.vue, frontend/src/views/system/dept/index.vue, frontend/src/views/system/dict/components/DataDrawer.vue, frontend/src/views/system/dict/index.vue, frontend/src/views/system/log/index.vue, frontend/src/views/system/menu/index.vue, frontend/src/views/system/notice/index.vue, frontend/src/views/system/position/index.vue, frontend/src/views/system/role/index.vue, frontend/src/views/system/user/index.vue
refactor: 移除未使用的ElementPlus导入和eslint相关依赖
=> fix: 替换ElMessage.info为ElMessageBox.close取消操作提示

frontend/vite.config.ts
简化vite配置，删除对vue、pinia和axios的手动分包规则，让构建工具自动处理
=> refactor(vite配置): 移除大型库的手动分包配置

deploy.sh, devops/nginx/nginx.conf, docker-compose.yaml, frontend/src/types/components.d.ts
调整docker compose日志显示方式，移除tail限制
修正nginx配置中的路径映射和路由规则
清理前端未使用的组件类型声明
=> fix(deploy): 修复容器日志显示和nginx配置路径问题

devops/nginx/nginx.conf, fastapp/README.md, fastapp/components.d.ts
更新README添加构建命令，优化nginx配置注释掉重复的index指令
移除fastapp中未使用的WdCheckbox组件声明
=> docs: 更新README和nginx配置，移除未使用的组件声明

backend/app/core/middlewares.py, deploy.sh, docker-compose.yaml
调整docker-compose中的前端路径映射，简化部署流程
优化部署脚本步骤顺序和日志输出
重构演示环境中间件的权限检查逻辑
=> fix(deploy): 更新部署脚本和配置路径

backend/env/.env.dev, backend/env/.env.prod
将生产环境数据库类型从sqlite改为mysql
更新开发环境的数据库名称
=> chore: 更新开发和生产环境的数据库配置

backend/requirements.txt
[更新 typer 和 pydantic-settings 版本以保持兼容 fastapi-mcp
=> fix(dependencies): 更新 typer 和 pydantic-settings 版本以保持兼容性

backend/app/core/validator.py
- 取消对 datetime 对象的格式化字符串序列化
- 保留原始 datetime 对象进行序列化处理
- 注释掉原有的 strftime 格式化代码以便回退检查
=> fix(core): 修正 DateTimeStr 序列化逻辑

frontend/src/views/system/ticket/index.vue
- 在工单列表工具栏新增刷新按钮
- 增加刷新按钮的提示工具提示
- 按钮样式使用主色调及圆形图标按钮
- 实现点击刷新按钮时调用刷新处理函数handleRefresh
=> feat(system): 添加工单列表刷新按钮

README.en.md, README.md
更新中英文README文件中的项目贡献列表，移除不再相关的项目，添加当前使用的主要依赖项
=> docs: 更新README中的项目贡献列表

backend/app/scripts/data/system_role_menus.json
- 系统角色菜单数据中添加缺失的菜单项
- 更新 system_role_menus.json 文件，增加 menu_id 116 的配置
=> fix(data): 修复系统角色菜单数据错误
